# Generated by Django 4.2.29 on 2026-03-26 21:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webhook', '0002_rawpost_status_correctionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.CharField(default='Lipa City LGU Official', max_length=100)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_comments', to='webhook.rawpost')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
