# Generated by Django 4.2.29 on 2026-03-26 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('triage', '0001_initial'),
        ('response', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoreply',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_replies', to='triage.report'),
        ),
    ]
