# Generated by Django 4.2.29 on 2026-03-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0003_add_for_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_manually_corrected',
            field=models.BooleanField(default=False, help_text='True once a moderator has saved any manual correction. Marks this record as ground-truth for future model training.'),
        ),
    ]
